logging:
    file:
        name: logging.log
    level:
        root: INFO
---
spring:
    profiles:
        active: dev
---
spring:
    application:
        name: demoservice
server:
    port: 8080
---
spring:
    profiles: dev
    application:
        name: demoservice
server:
 port: 9090
---
spring:
    profiles: prod
    application:
        name: demoservice
server:
    port: 4431